USE club_db;

CREATE TABLE USER (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    PERSONID BIGINT NOT NULL,
    ROLE VARCHAR(255) NOT NULL
);


CREATE TABLE PERSON (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    CEDULA BIGINT NOT NULL,
    CELLPHONE BIGINT NOT NULL
);

CREATE TABLE PARTNER (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    AMOUNT DOUBLE NOT NULL,
    PERSONID BIGINT NOT NULL,
    TYPE VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE GUEST (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    STATUS BOOLEAN NOT NULL,
    PERSONID BIGINT NOT NULL,
    PARTNERID BIGINT NOT NULL
);

-- create a admin user
INSERT INTO USER ( USERNAME, PASSWORD, PERSONID, ROLE) VALUES ( 'admin', 'admin', 1, 'admin');
INSERT INTO PERSON (NAME, CEDULA, CELLPHONE) VALUES ( 'admin', 1, 1);