CREATE TABLE USER (
    ID INT PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    PERSONID INT NOT NULL,
    ROLE VARCHAR(255) NOT NULL
);


CREATE TABLE PERSON (
    ID INT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    CEDULA INT NOT NULL,
    CELLPHONE INT NOT NULL
);

-- create a admin user
INSERT INTO USER (ID, USERNAME, PASSWORD, PERSONID, ROLE) VALUES (1, 'admin', 'admin', 1, 'admin');